# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'calculatrice.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(417, 495)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Montrer = QTextBrowser(self.centralwidget)
        self.Montrer.setObjectName(u"Montrer")
        self.Montrer.setGeometry(QRect(20, 10, 371, 81))
        self.Modulo = QPushButton(self.centralwidget)
        self.Modulo.setObjectName(u"Modulo")
        self.Modulo.setGeometry(QRect(10, 100, 90, 50))
        font = QFont()
        font.setPointSize(15)
        self.Modulo.setFont(font)
        self.ClearEverything = QPushButton(self.centralwidget)
        self.ClearEverything.setObjectName(u"ClearEverything")
        self.ClearEverything.setGeometry(QRect(110, 100, 90, 50))
        self.ClearEverything.setFont(font)
        self.Clear = QPushButton(self.centralwidget)
        self.Clear.setObjectName(u"Clear")
        self.Clear.setGeometry(QRect(210, 100, 90, 50))
        self.Clear.setFont(font)
        self.Erase = QPushButton(self.centralwidget)
        self.Erase.setObjectName(u"Erase")
        self.Erase.setGeometry(QRect(310, 100, 90, 50))
        font1 = QFont()
        font1.setPointSize(30)
        self.Erase.setFont(font1)
        self.fraction = QPushButton(self.centralwidget)
        self.fraction.setObjectName(u"fraction")
        self.fraction.setGeometry(QRect(10, 160, 90, 50))
        self.fraction.setFont(font)
        self.RootSquare = QPushButton(self.centralwidget)
        self.RootSquare.setObjectName(u"RootSquare")
        self.RootSquare.setGeometry(QRect(210, 160, 90, 50))
        self.RootSquare.setFont(font)
        self.Square = QPushButton(self.centralwidget)
        self.Square.setObjectName(u"Square")
        self.Square.setGeometry(QRect(110, 160, 90, 50))
        self.Square.setFont(font)
        self.Divise = QPushButton(self.centralwidget)
        self.Divise.setObjectName(u"Divise")
        self.Divise.setGeometry(QRect(310, 160, 90, 50))
        self.Divise.setFont(font)
        self.Multiply = QPushButton(self.centralwidget)
        self.Multiply.setObjectName(u"Multiply")
        self.Multiply.setGeometry(QRect(310, 220, 90, 50))
        self.Multiply.setFont(font1)
        self.num_7 = QPushButton(self.centralwidget)
        self.num_7.setObjectName(u"num_7")
        self.num_7.setGeometry(QRect(10, 220, 90, 50))
        font2 = QFont()
        font2.setPointSize(20)
        self.num_7.setFont(font2)
        self.num_8 = QPushButton(self.centralwidget)
        self.num_8.setObjectName(u"num_8")
        self.num_8.setGeometry(QRect(110, 220, 90, 50))
        self.num_8.setFont(font2)
        self.num_9 = QPushButton(self.centralwidget)
        self.num_9.setObjectName(u"num_9")
        self.num_9.setGeometry(QRect(210, 220, 90, 50))
        self.num_9.setFont(font2)
        self.num_5 = QPushButton(self.centralwidget)
        self.num_5.setObjectName(u"num_5")
        self.num_5.setGeometry(QRect(110, 280, 90, 50))
        self.num_5.setFont(font2)
        self.num_4 = QPushButton(self.centralwidget)
        self.num_4.setObjectName(u"num_4")
        self.num_4.setGeometry(QRect(10, 280, 90, 50))
        self.num_4.setFont(font2)
        self.Minus = QPushButton(self.centralwidget)
        self.Minus.setObjectName(u"Minus")
        self.Minus.setGeometry(QRect(310, 280, 90, 50))
        self.Minus.setFont(font1)
        self.num_6 = QPushButton(self.centralwidget)
        self.num_6.setObjectName(u"num_6")
        self.num_6.setGeometry(QRect(210, 280, 90, 50))
        self.num_6.setFont(font2)
        self.num_1 = QPushButton(self.centralwidget)
        self.num_1.setObjectName(u"num_1")
        self.num_1.setGeometry(QRect(10, 340, 90, 50))
        self.num_1.setFont(font2)
        self.num_2 = QPushButton(self.centralwidget)
        self.num_2.setObjectName(u"num_2")
        self.num_2.setGeometry(QRect(110, 340, 90, 50))
        self.num_2.setFont(font2)
        self.Plus = QPushButton(self.centralwidget)
        self.Plus.setObjectName(u"Plus")
        self.Plus.setGeometry(QRect(310, 340, 90, 50))
        self.Plus.setFont(font1)
        self.num_3 = QPushButton(self.centralwidget)
        self.num_3.setObjectName(u"num_3")
        self.num_3.setGeometry(QRect(210, 340, 90, 50))
        self.num_3.setFont(font2)
        self.dot = QPushButton(self.centralwidget)
        self.dot.setObjectName(u"dot")
        self.dot.setGeometry(QRect(210, 400, 90, 50))
        font3 = QFont()
        font3.setPointSize(25)
        self.dot.setFont(font3)
        self.Equal = QPushButton(self.centralwidget)
        self.Equal.setObjectName(u"Equal")
        self.Equal.setGeometry(QRect(310, 400, 90, 50))
        self.Equal.setFont(font1)
        self.num_0 = QPushButton(self.centralwidget)
        self.num_0.setObjectName(u"num_0")
        self.num_0.setGeometry(QRect(110, 400, 90, 50))
        self.num_0.setFont(font2)
        self.PositiveNegative_2 = QPushButton(self.centralwidget)
        self.PositiveNegative_2.setObjectName(u"PositiveNegative_2")
        self.PositiveNegative_2.setGeometry(QRect(10, 400, 90, 50))
        self.PositiveNegative_2.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 417, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Montrer.setMarkdown(QCoreApplication.translate("MainWindow", u"0\n"
"\n"
"", None))
        self.Montrer.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>", None))
        self.Modulo.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.ClearEverything.setText(QCoreApplication.translate("MainWindow", u"CE", None))
        self.Clear.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.Erase.setText(QCoreApplication.translate("MainWindow", u"<--", None))
        self.fraction.setText(QCoreApplication.translate("MainWindow", u"1/x", None))
        self.RootSquare.setText(QCoreApplication.translate("MainWindow", u"2\u221ax", None))
        self.Square.setText(QCoreApplication.translate("MainWindow", u"x2", None))
        self.Divise.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.Multiply.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.num_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.num_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.num_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.num_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.num_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.Minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.num_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.num_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.num_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.Plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.num_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.dot.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.Equal.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.num_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.PositiveNegative_2.setText(QCoreApplication.translate("MainWindow", u"+/-", None))
    # retranslateUi

